<?php

/** @var Mateusz\Mercetree\View\Data\ViewDataInterface $view */
/** @var Mateusz\Mercetree\TreeConfigurator\Configurator\SaleSummary\Presentation\ProductInterface $product */
/** @var Mateusz\Mercetree\Shop\ShopComponentInterface $shop */

$product = $view->get('product');
$shop = $view->get('shop');

$currencyFormatter = $shop->getCurrencyFormatter();

printf("\n# %s\nNET %11s\tGROSS %11s (VAT %d%% / %s)\n",
        $product->getName(),
        $currencyFormatter->format($product->getPriceNet(), $product->getCurrencySymbol()),
        $currencyFormatter->format($product->getPriceGross(), $product->getCurrencySymbol()),
        $product->getTaxRate(),
        $currencyFormatter->format($product->getTaxValue(), $product->getCurrencySymbol())
);
